name: wallflu
description: A new Flutter Wallpaper application for cross platform native.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  fluttertoast: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
  - images/flutterwithlogo.png
  - images/flutter_logo.png
  - images/aftrsplshbckgrnd.png

  fonts:
  - family: Aleo
    fonts:
    - asset: fonts/Aleo-Bold.ttf
    - asset: fonts/Aleo-BoldItalic.ttf
    - asset: fonts/Aleo-Italic.ttf




